version: '3.10'

services:
  mongo:
    image: mongo:6
    container_name: condo-track-mongodb
    networks:
      - condo-track-network
    volumes:
      - condo-track-data:/data/db
    restart: always

  api:
    build:
      context: ./code/back-end
      dockerfile: dockerfile
    container_name: condo-track-api
    env_file:
      - .env
    networks:
      - condo-track-network
    ports:
      - "8000:8000"
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=condo-track-mongodb
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./code/back-end:/app
    depends_on:
      - condo-track-mongodb
    restart: always

networks:
  condo-track-network:
    driver: bridge

volumes:
  condo-track-data:
    driver: local