FROM node:18.18.0
EXPOSE ${API_PORT}
WORKDIR /condo-track-api
ENV NODE_ENV=development
ENV API_PORT=8000
COPY package.json package-lock.json ./
COPY ./.env ./.env
COPY . .
RUN npm install
CMD [ "npm", "run", "start:dev" ]