FROM node:18.18.0
ENV NODE_ENV=development
ENV API_PORT=8000
WORKDIR /condo-track-api
COPY package.json ./
RUN npm install --legacy-peer-deps
COPY ./.env ./.env
COPY . .
EXPOSE ${API_PORT}
CMD [ "npm", "run", "start:dev" ]