name: Back-End CI

on:
  push:
    paths:
      - 'code/back-end/**'
    branches: [ "develop" ]
  pull_request:
    paths:
      - 'code/back-end/**'
    branches: [ "develop" ]

jobs:
  back-end-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: code/back-end

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
